`"libicu.dylib"2:(`loadicu;1);

\d l
\l l.k
\d .

I:0:"11.txt"
S:"\n"\"Οδυσσευς - Odysseus
Οδυσσεως - Odysseos
Οδυσσει - Odyssei
Οδυσσεα - Odyssea
Οδυσσευ - Odysseu"

lts:,/l.c "αβγδεζηθικλμνξοπρστυφχψως"
utf8:l.u8'lts
idx:@[!#1+lts;24;:;lts?**l.c"σ"]
nrm:25^idx lts?,/l.c iculow@

T:nrm'I
S:7#/:nrm'S
O:S[0;0]
odysse:24!1_-':6#*S

w:-1+&'odysse~/:/:5':'24!-':'T
+/,/24!R[1]@&|/'0,/:~^S?24!+'/R:1(S[0;0]-*:'')\idx@T@'w+/:\:\:!7

