I:0:"day21.txt"
a:a0:!/(`$;(@/|1((`I$;" "\)@"0:"'*:)\)')@'+": "\'I
fs:"+-*/"
op:fs!(+;-;*;!/-1 1*|:,)
inv:("-+/*";"--//")
coll:,`humn
up:{$[y~*|coll;coll,:x;]}
yell:{$[`i~@n:a[x];n;[a[x]:(op[*n@1])/o'r:`$n[0 2];up[x]'r;a[x]]]}
yell`root
oth:{*(`$(a0[y])_1)^x}.'+:
coll:+1_,':|coll
ot:1(a@)\oth@coll
res:**|ot
r:|1_'ot,-1#coll
slv:{f:op@inv[x;fs?y];f.(((::;|:)x&|/"+*"=y)z)}
{[ac;m;v;n](slv).f[0],r[1],,(ac;v)f:n=`$(r:a0@m)[0 2]}/[res;].r
